name: Build and push to ECR
description: 'Build and push to a ECR repository'
inputs:
  ecr_repository:
    description: 'ECR repository name'
    required: true
    type: string
  image_tag:
    description: 'Docker image tag'
    required: false
    default: 'latest'
    type: string
  build_args:
      description: 'Build arguments for docker build (comma separated, e.g. KEY1=value1,KEY2=value2)'
      required: false
      default: ''
      type: string
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'AWS region for ECR'
    required: false
    default: 'sa-east-1'
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr_repository }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      run: |
        # Parse build args if provided
        BUILD_ARGS=""
        if [ -n "${{ inputs.build_args }}" ]; then
          IFS=',' read -ra ARGS <<< "${{ inputs.build_args }}"
          for arg in "${ARGS[@]}"; do
            BUILD_ARGS="$BUILD_ARGS --build-arg $arg"
          done
        fi
        docker build $BUILD_ARGS \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
